### ISSUE TITLE
Pong fails to build.

### ISSUE THREAD

**Issue by hugo6390** [CeytiX/Pong#1]
Pong fails to build on my system with the following error message:
```
main.cpp: In function ‘int main()’:
main.cpp:63:65: warning: passing NULL to non-pointer argument 1 of ‘SDL_Surface* SDL_CreateRGBSurface(Uint32, int, int, int, Uint32, Uint32, Uint32, Uint32)’ [-Wconversion-null]
main.cpp:64:66: warning: passing NULL to non-pointer argument 1 of ‘SDL_Surface* SDL_CreateRGBSurface(Uint32, int, int, int, Uint32, Uint32, Uint32, Uint32)’ [-Wconversion-null]
main.cpp:65:54: warning: passing NULL to non-pointer argument 1 of ‘SDL_Surface* SDL_CreateRGBSurface(Uint32, int, int, int, Uint32, Uint32, Uint32, Uint32)’ [-Wconversion-null]
main.cpp:386:65: error: ‘lefySide’ was not declared in this scope
```

Please, provide a Makefile. Currently, it's really hard to compile your code, since the user doesn't have any informations about needed flags and supported compilers/systems.

**Comment by CeytiX** [comment]
Sorry,
I don't know how to compile a SDL program without code::blocks and i don't know how to create a makefile,
but i'll try to learn.
Thank you
(for me, it doesn't fail at lines 63,64 and 65)

**Comment by hugo6390** [comment]
Actually, the three lines you mentioned are just *warnings*, so that they don't lead the program to fail. The only *error* is at line 386.

Have a look at [this](http://stackoverflow.com/questions/9457225/codeblocks-verbose-build) discution, it may help you.

**Comment by CeytiX** [comment]
ok, i've corrected this error, but i won't create the makefile during the holidays

Do you know how to compile a SDL project with g++ (in terminal)?

**Comment by hugo6390** [comment]
After *git-pulling*, Pong still fails to build with the following error message:
```
main.cpp: In function ‘int main()’:
main.cpp:63:65: warning: passing NULL to non-pointer argument 1 of ‘SDL_Surface* SDL_CreateRGBSurface(Uint32, int, int, int, Uint32, Uint32, Uint32, Uint32)’ [-Wconversion-null]
main.cpp:64:66: warning: passing NULL to non-pointer argument 1 of ‘SDL_Surface* SDL_CreateRGBSurface(Uint32, int, int, int, Uint32, Uint32, Uint32, Uint32)’ [-Wconversion-null]
main.cpp:65:54: warning: passing NULL to non-pointer argument 1 of ‘SDL_Surface* SDL_CreateRGBSurface(Uint32, int, int, int, Uint32, Uint32, Uint32, Uint32)’ [-Wconversion-null]
/tmp/ccqOk5IV.o: In function `levelChoice(SDL_Surface*)':
main.cpp:(.text+0x69): undefined reference to `IMG_Load'
main.cpp:(.text+0x77): undefined reference to `IMG_Load'
main.cpp:(.text+0x85): undefined reference to `IMG_Load'
main.cpp:(.text+0x93): undefined reference to `IMG_Load'
main.cpp:(.text+0xa1): undefined reference to `IMG_Load'
/tmp/ccqOk5IV.o:main.cpp:(.text+0xaf): more undefined references to `IMG_Load' follow
collect2: error: ld returned 1 exit status
```

I'm not an expert, but I think you could try to build your project with following command:
```
g++ -o Pong main.cpp `sdl-config --cflags --libs`
```

**Comment by CeytiX** [comment]
there are  2 libs:
SDL and SDL_image; IMG_Load( ) need SDL_image

**Comment by CeytiX** [comment]
i've found a command which compiles the project:
```
g++ main.cpp -o Pong `sdl-config --cflags --libs` -lSDL -lSDLmain -lSDL_image -O2 -s
```

You need SDL and SDL_image:
```
sudo apt-get install libsdl1.2-dev
sudo apt-get install libsdl-image1.2 libsdl-image1.2-dev
```

**Comment by CeytiX** [comment]
I've created the makefile and you can try to compile the project

**Comment by hugo6390** [comment]
Great, it works ! :smiley:

Just out of curiosity, is it an hand-written Makefile ?

**Comment by CeytiX** [comment]
Yes, it is ;)

**Comment by CeytiX** [comment]
You can compile the snake too,  I've done the makefile and I've written the commands to install libs in the readme

**Comment by hugo6390** [comment]
After looking at it, I think you might simplify your Makefile:
```
CC=g++
CFLAGS=`sdl-config --cflags --libs` -lSDL -lSDLmain -lSDL_image -O2 -s
EXEC=Pong

all:
        $(CC) main.cpp -o $(EXEC) $(CFLAGS)
```

It seems to be easier to read (but, don't feel obliged to use it, it's just a (maybe non-working) suggestion).

**Comment by CeytiX** [comment]
It works, thank you

**Comment by hugo6390** [comment]
It would be also better to fix these compilation warnings. Pong isn't a big software, it should be relatively easily fixed.

**Comment by CeytiX** [comment]
the warnings are fixed, you can clone the project

**Comment by CeytiX** [comment]
the warning of snake is fixed

**Comment by CeytiX** [comment]
I can compile the project on my computer, but I can't on my father's computer, do you know why ?

**Comment by hugo6390** [comment]
Please, provide more informations. What are you thinking with *I can't* ? Are there error messages ? How are you compiling ? What's your father's computer ?

**Comment by CeytiX** [comment]
I've downloaded the zip of my project on his computer and installed SDL/SDL_image/SDL_ttf;
i used the makefile and there aren't errors/warnings; but the game didn't work when I tried to run the program.

His computer use Ubuntu 10.4

**Comment by hugo6390** [comment]
How are you executing the binary ?

**Comment by CeytiX** [comment]
without terminal

**Comment by CeytiX** [comment]
i tried to use `./Snake`, but it didn't run

**Comment by hugo6390** [comment]
Without any error message ?

Try to compile with:
```
g++ main.cpp -o Pong `sdl-config --cflags --libs` -lSDL -lSDLmain -lSDL_image -O1 -Wall -Wextra
```
and try `gdb Pong` and `run`.

`-Wall -Wextra` should generate a lot of warnings. Look at it, it may be useful (or not!).

**Comment by CeytiX** [comment]
Thank you,but I can't try today, i'll try tomorrow,
Bye

**Comment by CeytiX** [comment]
I didn't understand why,  but the binary run when I compile without O2 and s, 
So I removed these options in makefile

**Comment by hugo6390** [comment]
Please, revert your changes and close this issue. I'll send you an email.
